/**
 * Disaster Management Reports & Early Warning Bulletin Generator
 */

import React, { useState } from 'react';
import { MonitoredLocation, AlertNotification, StateRiskSummary } from '../types/landslide';
import { 
  FileText, 
  Download, 
  Share2, 
  Printer, 
  CheckCircle2, 
  ShieldAlert, 
  Send, 
  Radio, 
  Building2 
} from 'lucide-react';

interface ReportsPanelProps {
  locations: MonitoredLocation[];
  alerts: AlertNotification[];
  stateSummaries: StateRiskSummary[];
}

export const ReportsPanel: React.FC<ReportsPanelProps> = ({
  locations,
  alerts,
  stateSummaries
}) => {
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  const handleDownloadReport = (format: 'PDF' | 'CSV' | 'JSON') => {
    let content = '';
    let filename = `NER_LandslideGuard_Daily_Bulletin_${new Date().toISOString().slice(0, 10)}`;
    let mimeType = 'text/plain';

    if (format === 'JSON') {
      content = JSON.stringify(
        {
          timestamp: new Date().toISOString(),
          system: 'BhooSuraksha Command Center',
          disclaimer: 'PROTOTYPE DEMONSTRATION DATA - NOT SCIENTIFICALLY CERTIFIED',
          monitoredLocations: locations,
          activeAlerts: alerts,
          stateSummaries
        },
        null,
        2
      );
      filename += '.json';
      mimeType = 'application/json';
    } else if (format === 'CSV') {
      const headers = 'ID,Name,State,District,Latitude,Longitude,RiskProbability,RiskLevel,Rainfall24h,SoilMoisture,Slope,GeofenceActive\n';
      const rows = locations
        .map(
          l =>
            `"${l.id}","${l.name}","${l.state}","${l.district}",${l.latitude},${l.longitude},${l.risk_probability},"${l.risk_level}",${l.parameters.rainfall_24h},${l.parameters.soil_moisture},${l.parameters.slope},${l.has_active_geofence}`
        )
        .join('\n');
      content = headers + rows;
      filename += '.csv';
      mimeType = 'text/csv';
    } else {
      // Formatted text bulletin for PDF/Print
      content = `======================================================================
NORTH EASTERN REGION (NER) LANDSLIDE RISK & EARLY WARNING BULLETIN
Issued by: BhooSuraksha Prototype Disaster Management System
Timestamp: ${new Date().toLocaleString()}
Status: DEMO / OPERATIONAL PROTOTYPE
======================================================================

1. REGIONAL EXECUTIVE SUMMARY:
- Total Monitored Slope Sectors: ${locations.length}
- Critical Risk Zones (Prob >= 85%): ${locations.filter(l => l.risk_probability >= 0.85).length}
- High Risk Zones (Prob >= 70%): ${locations.filter(l => l.risk_probability >= 0.70 && l.risk_probability < 0.85).length}
- Active Automated Geofences: ${locations.filter(l => l.has_active_geofence).length}

2. CRITICAL SECTORS REQUIRING IMMEDIATE FIELD RECONNAISSANCE:
${locations
  .filter(l => l.risk_probability >= 0.70)
  .map(
    l =>
      `• [${l.risk_level}] ${l.name}, ${l.district} (${l.state}) - Prob: ${(l.risk_probability * 100).toFixed(0)}%
   Rainfall: ${l.parameters.rainfall_24h}mm | Soil Moisture: ${l.parameters.soil_moisture}% | Slope: ${l.parameters.slope}°
   Geofence Radius: ${l.geofence_radius_km} km | Vulnerability: ${l.parameters.geological_susceptibility}`
  )
  .join('\n\n')}

3. STATE VULNERABILITY BREAKDOWN:
${stateSummaries.map(s => `• ${s.state}: ${s.totalZones} sites monitored (${s.criticalZones} critical, ${s.highRiskZones} high risk). Avg Rain: ${s.avgRainfall24h}mm`).join('\n')}

======================================================================
NOTICE: This bulletin was generated by the BhooSuraksha prototype.
Predictions represent automated algorithmic evaluations.
======================================================================`;
      filename += '.txt';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloadSuccess(`Generated and downloaded ${filename}`);
    setTimeout(() => setDownloadSuccess(null), 4000);
  };

  return (
    <div id="reports-panel-container" class="space-y-6">
      {/* Header */}
      <div class="bg-slate-900/90 border border-slate-800 p-4 rounded-xl backdrop-blur shadow-xl flex flex-wrap items-center justify-between gap-4">
        <div class="flex items-center gap-3">
          <div class="p-2.5 rounded-xl bg-indigo-950/80 border border-indigo-800 text-indigo-400">
            <FileText class="w-6 h-6" />
          </div>
          <div>
            <h2 class="text-lg font-bold text-slate-50">Daily Bulletins & Situation Briefings</h2>
            <p class="text-xs text-slate-400">
              Export geospatial hazard logs, emergency alerts, and inter-agency coordination dossiers
            </p>
          </div>
        </div>

        {/* Export Buttons */}
        <div class="flex items-center gap-2">
          <button
            onClick={() => handleDownloadReport('PDF')}
            class="px-3 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition shadow cursor-pointer"
          >
            <Printer class="w-3.5 h-3.5" />
            <span>Generate Situation Report</span>
          </button>
          <button
            onClick={() => handleDownloadReport('CSV')}
            class="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer"
          >
            <Download class="w-3.5 h-3.5" />
            <span>Export CSV</span>
          </button>
          <button
            onClick={() => handleDownloadReport('JSON')}
            class="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer"
          >
            <Download class="w-3.5 h-3.5" />
            <span>GeoJSON Telemetry</span>
          </button>
        </div>
      </div>

      {downloadSuccess && (
        <div class="p-3 bg-emerald-950/60 border border-emerald-800 text-emerald-300 text-xs rounded-xl flex items-center gap-2">
          <CheckCircle2 class="w-4 h-4 text-emerald-400" />
          <span>{downloadSuccess}</span>
        </div>
      )}

      {/* Broadcast Dispatch Channels Preview */}
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div class="bg-slate-900/80 border border-slate-800 rounded-xl p-4 shadow-lg">
          <div class="flex items-center gap-2 mb-2 text-indigo-400">
            <Building2 class="w-4 h-4" />
            <h3 class="text-xs font-bold uppercase tracking-wider">SDMA / DDMA Feeds</h3>
          </div>
          <p class="text-xs text-slate-300 mb-3">
            Automated Common Alerting Protocol (CAP India) XML packets dispatched directly to State Disaster Management Authorities.
          </p>
          <div class="p-2 rounded bg-slate-950/60 border border-slate-800 text-xs text-slate-400 font-mono">
            Target: 8 State EOCs • Sync: Continuous
          </div>
        </div>

        <div class="bg-slate-900/80 border border-slate-800 rounded-xl p-4 shadow-lg">
          <div class="flex items-center gap-2 mb-2 text-amber-400">
            <Radio class="w-4 h-4" />
            <h3 class="text-xs font-bold uppercase tracking-wider">Border Roads Org (BRO)</h3>
          </div>
          <p class="text-xs text-slate-300 mb-3">
            Corridor slope failure vulnerability feeds along strategic national highways (NH-10, NH-29, NH-102, NH-44).
          </p>
          <div class="p-2 rounded bg-slate-950/60 border border-slate-800 text-xs text-slate-400 font-mono">
            Target: Project Vartak, Sewak, Swastik
          </div>
        </div>

        <div class="bg-slate-900/80 border border-slate-800 rounded-xl p-4 shadow-lg">
          <div class="flex items-center gap-2 mb-2 text-rose-400">
            <ShieldAlert class="w-4 h-4" />
            <h3 class="text-xs font-bold uppercase tracking-wider">SDRF & NDRF Battalions</h3>
          </div>
          <p class="text-xs text-slate-300 mb-3">
            Pre-positioning advisories for heavy hydraulic excavators and search-and-rescue units in predicted landslide threat cones.
          </p>
          <div class="p-2 rounded bg-slate-950/60 border border-slate-800 text-xs text-slate-400 font-mono">
            Target: 1st, 12th NDRF Battalions
          </div>
        </div>
      </div>
    </div>
  );
};
